feat: add CloudWatch event rules and add missed CloudWatch log outputs
cloudposse/terraform-aws-lambda-function pull request #35
Opened 2023-01-06 01:40 UTC by arichtman

## what
* add CloudWatch event rules
* add missed CloudWatch log outputs
* remove variable `sns_subscriptions`

## why
* CloudWatch event rules are useful for invoking lambda by cron expressions
* CloudWatch log out puts are useful for external usage
* `sns_subscriptions` is an unused variables

## references
* `Closes #27 `

2023-01-06 01:41 UTC, arichtman commented
This is a resubmission of #29

2023-10-12 16:24 UTC, Gowiem requested changes

2023-10-12 16:24 UTC, Gowiem commented on variables.tf
> +  type        = list(any)
Can we update this to a list of objects here?

2023-10-12 16:26 UTC, Gowiem commented
@arichtman sorry we've let this sit un-reviewed for so long. I can help drive it forward if you're willing to pick it back up as it looks like a good addition of functionality that we'd appreciate to get into the project. Can you pull in `main` locally, deal with conflicts, address feedback, and push your changes? Please ping me when it's ready and I'll be happy to review. Thanks for the contribution and I look forward to getting this in!

2023-10-13 22:45 UTC, arichtman commented
@SweetOps has done the work here so far. I didn't want to steal anyone's credit so this is just a resubmission of the PR. I don't have access to this repository to make any adjustments.

2023-11-29 04:23 UTC, SweetOps commented
> I didn't want to steal anyone's credit so this is just a resubmission of the PR.

@arichtman, I do appreciate it. However, feel free to open PR from the your repo if you're still interested in these changes.

2024-03-10 01:00 UTC, closed without merging